### ISSUE TITLE
Easier to use official ROCm docker images

### ISSUE THREAD

**Issue by hartmark** [HardAndHeavy/stable-diffusion-webui-rocm-docker#1]
I'm quite new to stable diffusion and found this blog about how to use it in a docker container.

https://prog.world/running-stable-diffusion-on-amd-radeon-gpu-in-docker/

I tried your Dockerfiles and it worked nice for my AMD Radeon 7800 XT aswell.

However I felt that the process of having your gigantic Makefile for cooking the image to be a bit too complex and error prone.

There's also a trust issue because your way uses your own docker image as base. It's not that I don't trust you but I think it's better to use a more standard image as base because that way you don't have to care about maintaining it and update if any new versions comes.

Amd has official images with pytorch already preinstalled so that way reduces the time spent to set it up significantly.

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/3rd-party/pytorch-install.html#

You just need two files now:

`% cat docker-compose.yml`
```
services:
  stable-diffusion-webui:
    image: rocm/pytorch:latest
    ports:
      - "80:80"
    restart: unless-stopped
    command: ["/sd-webui/startup.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/stable-diffusion:/stable-diffusion
      - ./data/sd-webui:/sd-webui
      - ./startup.sh:/sd-webui/startup.sh
```
`% cat startup.sh`
```
#!/bin/sh

# NOTE: This is to be run in docker container, not the host

git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /sd-webui
pip install insightface

cd /sd-webui
python3 launch.py \
	--no-half \
	--precision=full \
	--port 80 \
	--listen \
	--enable-insecure-extension-access \
	--data-dir=/stable-diffusion

```

To run, just run this command:
`sudo docker-compose up --force-recreate`

That way you just have a clean slate every time you startup your container.

And to put it in the backgrouund, just add `-d`
